---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(readxl)
library(janitor)

lista_UF_cobertura = list.files() 

# Lista todos os arquivos CSV no diretório
arquivos_xlsx <- list.files(here(), pattern = "\\.xlsx$", full.names = F)

#Criar funcao
read_xl_sipni <- function(arquivo) {
  dados <- read_excel(arquivo, skip = 4, col_names = FALSE) %>%
    setNames(.[1, ]) %>%
    slice(-1:-4) %>%
    mutate(across(-1, as.numeric)) %>%  
    pivot_longer(cols = -c(1), 
                 names_to = "imuno", 
                 values_to = "cobertura") %>% 
    mutate(arquivo = basename(arquivo)) %>% 
    janitor::clean_names() %>% 
    mutate(cobertura = round(cobertura, 2),
           ano = as.numeric(gsub(".*_(\\d{4})\\.xlsx", "\\1", arquivo)),
           uf = gsub("\\d", "", .[[1]]))  %>% 
    select(-unidade_da_federacao) %>% 
    filter(!is.na(uf),
           !grepl("Gerado", uf)) %>% 
    select(uf, ano, imuno, cobertura) %>% 
    group_by(uf, ano, imuno)
  
  return(dados)
}


# Leia, pivot_longer e combine os arquivos CSV em um único DataFrame
sipni_cobertura_uf_1994_2023 <- lapply(arquivos_xlsx, read_xl_sipni) %>%
  bind_rows()

write.csv(sipni_cobertura_uf_1994_2023, file = "sipni_cobertura_uf_1994_2023.csv")

```

```{r}
lista_MU_cobertura = list.files() 
arquivos_xlsx <- list.files(here(), pattern = "\\.xlsx$", full.names = F)

#Criar funcao
read_xl_sipni_municipio <- function(arquivo) {
  dados <- read_excel(arquivo, skip = 4, col_names = FALSE) %>%
    setNames(.[1, ]) %>%
    slice(-1:-4) %>%
    mutate(across(-1, as.numeric)) %>%  
    pivot_longer(cols = -c(1), 
                 names_to = "imuno", 
                 values_to = "cobertura") %>% 
    mutate(arquivo = basename(arquivo)) %>% 
    janitor::clean_names() %>% 
    mutate(cobertura = round(cobertura, 2),
           ano = as.numeric(gsub(".*_(\\d{4})\\.xlsx", "\\1", arquivo))) %>% 
    filter(!is.na(municipio),
           !grepl("Gerado", municipio)) %>% 
    select(municipio, ano, imuno, cobertura) %>% 
    group_by(municipio, ano, imuno)
  
  return(dados)
}


# Leia, pivot_longer e combine os arquivos CSV em um único DataFrame
sipni_cobertura_municipios_1994_2023 <- lapply(arquivos_xlsx, read_xl_sipni_municipio) %>%
  bind_rows()

write.csv(sipni_cobertura_municipios_1994_2023, file = "sipni_cobertura_municipios_1994_2023.csv")



```




